### PR TITLE
fix: windows build

### PR DESCRIPTION
**Pull request by mastilver**
see: https://github.com/addaleax/lzma-native/issues/5

### CODE REVIEW

**Comment by addaleax** [comment]
@mastilver If you include the changes to travis.yml from #2, the build will also pass on Travis because the more recent versions of `nan` require a C++11 compiler (I’d close my PR then)

**Comment by mastilver** [comment]
@addaleax I don't mind, neither I wouldn't mind if you set an higher version on your PR ;)
I just need a working version for windows, if travis pass it's even better :D

I will do it in a couple of hours (if you don't update #2 in the meantime)

**Comment by addaleax** [comment]
Ok, I updated #2 :)

**Comment by mastilver** [comment]
:+1: cool, thank you!

**Pull request closed without merging**
